name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5
 
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: azure/k8s-actions/k8s-set-context@master
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - uses: azure/k8s-actions/k8s-deploy@master
      with:
        manifests: |
          test.yaml
